name: revision
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - binutils_impl_linux-64=2.40=h5293946_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.4.26=py39h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cpython=3.9.22=py39hd8ed1ab_1
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gcc=13.3.0=h9576a4e_1
  - gcc_impl_linux-64=13.3.0=hfea6d02_1
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gxx=13.3.0=h9576a4e_1
  - gxx_impl_linux-64=13.3.0=hdbfa832_1
  - idna=3.7=py39h06a4308_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py39h06a4308_1
  - jpeg=9e=h5eee18b_3
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=13.3.0=h84ea5a7_101
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpng=1.6.39=h5eee18b_0
  - libsanitizer=13.3.0=heb74ff8_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=13.3.0=h84ea5a7_101
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - numexpr=2.10.1=py39h3c60e43_0
  - numpy=2.0.1=py39h5f9d8c6_1
  - numpy-base=2.0.1=py39hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.2=py39h06a4308_0
  - pandas=2.2.3=py39h6a678d5_0
  - pillow=10.4.0=py39h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - pyparsing=3.2.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.20=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=2.5.1=py3.9_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_1
  - seaborn=0.13.2=py39h06a4308_3
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h4a8ded7_18
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.5.1=py39_cu124
  - torchtriton=3.1.0=py39
  - torchvision=0.20.1=py39_cu124
  - unicodedata2=15.1.0=py39h5eee18b_1
  - urllib3=2.2.3=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - bitsandbytes==0.45.5
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.1.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.5
      - exceptiongroup==1.2.2
      - fire==0.7.0
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - hf-xet==1.1.5
      - huggingface-hub==0.26.2
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lxml==5.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nltk==3.9.1
      - openpyxl==3.1.5
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - portalocker==2.0.0
      - propcache==0.2.0
      - protobuf==5.29.2
      - psutil==6.1.0
      - pyarrow==18.0.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pytest==8.3.3
      - pytz==2024.2
      - regex==2024.11.6
      - rouge-score==0.1.2
      - sacrebleu==1.5.1
      - sacremoses==0.1.1
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - tomli==2.1.0
      - tqdm==4.67.0
      - transformers==4.46.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - wandb==0.19.1
      - xxhash==3.5.0
      - yarl==1.17.1
prefix: /home/azureuser/anaconda3/envs/revision
